### ISSUE TITLE
不知道这是什么错误

### ISSUE THREAD

**Issue by zhmbobo** [Anonym-w/autoSigninAliyun#4]
## 开始执行... 2023-02-14 17:10:25

/ql/data/scripts/autoSignin.js:11
const fetch = require("node-fetch")
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /root/.local/share/pnpm/global/5/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/index.js from /ql/data/scripts/autoSignin.js not supported.
Instead change the require of index.js in /ql/data/scripts/autoSignin.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/ql/data/scripts/autoSignin.js:11:15) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.12.1

## 执行结束... 2023-02-14 17:10:26  耗时 1 秒

**Comment by 2hacc** [comment]
我也是遇到这样的问题，不知道作者能不能看到留言。我感觉说明应该详细点，比如要安装node-fetch依赖之类的

**Comment by Sharplee** [comment]
安装了node-fetch依赖 依然报错。

**Comment by Sharplee** [comment]
node-fetch 版本过高  目前有解决办法 但是如果设置了 其他的任务又会有问题，算了 这个先不弄了。。。

**Comment by Anonym-w** [comment]
我用的版本是 node-fetch@2 ,在 依赖管理 - NodeJs - 新建依赖 - 名称输入:node-fetch@2 ,这个只是一个调用http的工具,如果实在有问题可以换成其他的,比如 axios

**Comment by zhmbobo** [comment]
按照

> ## 开始执行... 2023-02-14 17:10:25
> /ql/data/scripts/autoSignin.js:11 const fetch = require("node-fetch") ^
> 
> Error [ERR_REQUIRE_ESM]: require() of ES Module /root/.local/share/pnpm/global/5/.pnpm/node-fetch@3.3.0/node_modules/node-fetch/src/index.js from /ql/data/scripts/autoSignin.js not supported. Instead change the require of index.js in /ql/data/scripts/autoSignin.js to a dynamic import() which is available in all CommonJS modules. at Object. (/ql/data/scripts/autoSignin.js:11:15) { code: 'ERR_REQUIRE_ESM' }
> 
> Node.js v18.12.1
> 
> ## 执行结束... 2023-02-14 17:10:26 耗时 1 秒

删除了容器和镜像，从新安装。按照[g群](https://t.me/scriptalking/2146) 里的 [一键脚本](https://thin-hill-428.notion.site/QL-pannel-Faker-Repository-environment-Setup-45edcbfe90d74d8abb2d71896eab3be7) 从新安装，一路默认回车。然后安装教程，执行一键拉库，安装完成之后，完美运行脚本。
并没有在面板的依赖管理里添加任何依赖，就能完美执行。
**感谢大佬的脚本！**

**Comment by 2hacc** [comment]
你试试我的最新地址  https://tv.5ye.cc  一定要用https 这是放在服务器里面的，速度快稳定。
你也可以去我的网站看看其他的接口  www.2ha.cc

zhmbobo ***@***.***> 于2023年2月17日周五 19:24写道：
